# ░██████╗██╗░░██╗██╗░░░██╗██╗░░░░░██╗░░░░░░░░░░░░██████╗██╗░░░██╗░██████╗████████╗███████╗███╗░░░███╗
# ██╔════╝██║░██╔╝██║░░░██║██║░░░░░██║░░░░░░░░░░░██╔════╝╚██╗░██╔╝██╔════╝╚══██╔══╝██╔════╝████╗░████║
# ╚█████╗░█████═╝░██║░░░██║██║░░░░░██║░░░░░█████╗╚█████╗░░╚████╔╝░╚█████╗░░░░██║░░░█████╗░░██╔████╔██║
# ░╚═══██╗██╔═██╗░██║░░░██║██║░░░░░██║░░░░░╚════╝░╚═══██╗░░╚██╔╝░░░╚═══██╗░░░██║░░░██╔══╝░░██║╚██╔╝██║
# ██████╔╝██║░╚██╗╚██████╔╝███████╗███████╗░░░░░░██████╔╝░░░██║░░░██████╔╝░░░██║░░░███████╗██║░╚═╝░██║
# ╚═════╝░╚═╝░░╚═╝░╚═════╝░╚══════╝╚══════╝░░░░░░╚═════╝░░░░╚═╝░░░╚═════╝░░░░╚═╝░░░╚══════╝╚═╝░░░░░╚═╝

# This is the prefix that will be shown every time you type the command. If you would like to use hex colors please
# use #13F94E as so just change to which color you would like. This does work with normal minecraft colors as well.
General:
    Command-Prefix: "<#13F94E>&l● SKULLS &8&l➤"
    Smelter-Prefix: "<#13F94E>&l● SMELTER &8&l➤"
    
# If you would like to change which language that is being used in the skript this is where it would be changed.
Language: lang-en.yml
    
    
# This is where you find the lore of the skulls that will be dropped after a hostile/passive mob is killed.
Skull-lore:
- "&7Turn in this Skull at spawn or &b/smelter &7to"
- "&7unlock &aSpawners&7 or earn &aMoney&7!"
