# ░██████╗██╗░░██╗██╗░░░██╗██╗░░░░░██╗░░░░░░░░░░░░██████╗██╗░░░██╗░██████╗████████╗███████╗███╗░░░███╗
# ██╔════╝██║░██╔╝██║░░░██║██║░░░░░██║░░░░░░░░░░░██╔════╝╚██╗░██╔╝██╔════╝╚══██╔══╝██╔════╝████╗░████║
# ╚█████╗░█████═╝░██║░░░██║██║░░░░░██║░░░░░█████╗╚█████╗░░╚████╔╝░╚█████╗░░░░██║░░░█████╗░░██╔████╔██║
# ░╚═══██╗██╔═██╗░██║░░░██║██║░░░░░██║░░░░░╚════╝░╚═══██╗░░╚██╔╝░░░╚═══██╗░░░██║░░░██╔══╝░░██║╚██╔╝██║
# ██████╔╝██║░╚██╗╚██████╔╝███████╗███████╗░░░░░░██████╔╝░░░██║░░░██████╔╝░░░██║░░░███████╗██║░╚═╝░██║
# ╚═════╝░╚═╝░░╚═╝░╚═════╝░╚══════╝╚══════╝░░░░░░╚═════╝░░░░╚═╝░░░╚═════╝░░░░╚═╝░░░╚══════╝╚═╝░░░░░╚═╝

General:
    Command-Prefix: "<#13F94E>&l● SKULLS &8&l➤"
    Smelter-Prefix: "<#13F94E>&l● SMELTER &8&l➤"
